service: smarthome-api
frameworkVersion: '3.22.0'

package:
  excludeDevDependencies: true
  exclude:
    - src/**  # Don't package up raw .ts files. We only care about /build/

custom:
  # Use the --stage CLI option if it exists, otherwise use the default stage specified by provider.stage
  stage: ${opt:stage, self:provider.stage}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  stage: dev
  profile: ${env:IAM_PROFILE}  # AWS credentials profile
  region: us-east-1  # Has to be us-east-1 to make custom domains work with serverless
  memorySize: 512
  timeout: 6
  logRetentionInDays: 14
  httpApi:
    cors:
      allowedOrigins:
        - ${env:DOMAIN}
        - ${env:DEV_DOMAIN}
      allowedMethods:
        - GET
        - OPTIONS
        - POST
        - PUT
        - DELETE
      allowedHeaders:
        # FIXME: What should be included here? Do we need additional cloudfront headers?
        - Content-Type
        - X-Amz-Date
        - Authorization
        - X-Api-Key
        - X-Amz-Security-Token
        - X-Amz-User-Agent
        - X-Transaction-Key
        - Access-Control-Allow-Origin
      allowCredentials: true
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - logs:GetLogEvents
      Resource: '*'
  environment:
    # Allows us to reference variables in code with process.env.<KEY>
    STAGE: ${self:custom.stage}

functions:
  # Authentication
  auth:
    handler: build/handlers/auth.handler
    events:
      - httpApi:
          path: /auth
          method: POST
      - httpApi:
          path: /auth
          method: GET
  # Devices
  devices:
    handler: build/handlers/devices.handler
    events:
      - httpApi:
          path: /devices
          method: GET
  # Temperature
  temperature:
    handler: build/handlers/temperature.handler
    events:
      - httpApi:
          path: /temperature
          method: GET
      - httpApi:
          path: /temperature
          method: POST
  # Outside temp (scheduled)
  outsideTemp:
    handler: build/handlers/outside-temp.handler
    events:
      - schedule: rate(30 minutes)

resources:
  - ${file(resources/dynamodb.yml)}

