Resources:
    # Temperature
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:APP_NAME}-${self:custom.stage}-temperatures
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH  # Partition key
          - AttributeName: timestamp
            KeyType: RANGE  # Sort key
        TimeToLiveSpecification:
          AttributeName: ttl
          Enabled: true
