Resources:
    # Devices
    deviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:APP_NAME}-${self:custom.stage}-devices
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH  # Partition key
    # Temperature
    temperatureTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:APP_NAME}-${self:custom.stage}-temperature
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH  # Partition key
          - AttributeName: timestamp
            KeyType: RANGE  # Sort key
    # Humidity
    humidityTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${env:APP_NAME}-${self:custom.stage}-humidity
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: deviceId
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: N
        KeySchema:
          - AttributeName: deviceId
            KeyType: HASH  # Partition key
          - AttributeName: timestamp
            KeyType: RANGE  # Sort key
